name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.14-dev
          - os: macos-latest
            python-version: 3.12
          - os: windows-latest
            python-version: 3.6
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install wheel
      - run: pip install -e .[test]

      - run: pytest
