---
name: Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.12
          - os: ubuntu-20.04
            python-version: 3.6
          - os: macos-latest
            python-version: 3.12
          - os: windows-latest
            python-version: 3.9
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install wheel
      - run: pip install -e .[test]

      - run: pytest
